# workflow 의 이름
name: Build Wable
on:
  push:
    branches: [ setting#116-github-action ]
jobs:
  build:
    name: Build Project
    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v2
        - name: Install Dependencies
          run: swift package resolve
        - name: Build
          run: xcodebuild -project Wable-iOS.xcodeproj -scheme Wable-iOS -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 13 mini'
