# workflow 의 이름
name: Build Wable
on:
  push:
    branches: [ setting#116-github-action ]
jobs:
  build:
    name: Build Project
    runs-on: macos-latest
    steps:
        - name: Checkout the code
          uses: actions/checkout@v2
        - name: Build
          run: xcodebuild clean build -project Wable-iOS.xcodeproj -scheme Wable-iOS -configuration Debug -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 13 mini'
